#!/bin/sh

if [ "$ENV0" != "AAAAA" ] ; then
        echo Undefined ENV0.
        exit 12
fi
echo $ENV0

if [ "$ENV2" != "BBBB" ] ; then
    echo Undefined ENV2.
    exit 12
fi
echo $ENV2
if [ "$TESTENV1" != "ENVENV" ] ; then
    echo Undefined TESTENV1.
    exit 12
fi
if [ "$1" != "XX" ] ; then
        echo Invalid Arg#1.
        exit 12
fi
echo $TESTENV1 $1
if [ "$2" == "" ] ; then
        echo Invalid Arg#2
        exit 12
fi
exit $2

